// GERADO a partir de santoral-completo.pdf (Calendario Serafico, p. 37-44).
// Fonte fuzzy (PDF 2 colunas). Campos liturgicos precisam de revisao editorial.
// Dezembro truncado na fonte (indice termina em 02/dez; p. 45 inicia outra secao).
// shortHistory fica null ate curadoria; premium default true; nao editar a mao sem re-gerar.

import type { SaintDay } from "./santoral.ts";

export const franciscanSantoral2026: SaintDay[] = [
  {
    id: "saint-01-03-santissimo-nome-de-jesus",
    monthDay: "01-03",
    name: "Santíssimo Nome de Jesus",
    qualifiers: [],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: "santissimo-nome-de-jesus",
  },
  {
    id: "saint-01-04-santa-angela-de-foligno-religiosa",
    monthDay: "01-04",
    name: "Santa Ângela de Foligno, religiosa",
    qualifiers: ["religioso"],
    order: "third",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }, { jurisdiction: "TOR", rank: "memoria_facultativa" }, { jurisdiction: "OFS", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-05-bem-aventurado-diego-jose-de-cadiz-presbitero",
    monthDay: "01-05",
    name: "Bem-aventurado Diego José de Cádiz, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-12-sao-bernardo-de-corleone-religioso",
    monthDay: "01-12",
    name: "São Bernardo de Corleone, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-14-bem-aventurado-odorico-de-pordenone-presbitero",
    monthDay: "01-14",
    name: "Bem-aventurado Odorico de Pordenone, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }, { jurisdiction: "OFMConv", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-16-sao-berardo-e-seus-companheiros-protomartires",
    monthDay: "01-16",
    name: "São Berardo e seus companheiros, protomártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-19-santa-eustoquia-calafato-virgem",
    monthDay: "01-19",
    name: "Santa Eustóquia Calafato, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-20-bem-aventurado-joao-batista-triquerie-presbitero-e-martir",
    monthDay: "01-20",
    name: "Bem-aventurado João Batista Triquerie, presbítero e mártir",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-27-santa-angela-de-merici-virgem",
    monthDay: "01-27",
    name: "Santa Ângela de Mérici, virgem",
    qualifiers: ["virgem"],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "memoria_facultativa" }, { jurisdiction: "TOFr", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-29-bem-aventurado-francisco-zirano-presbitero-e-martir",
    monthDay: "01-29",
    name: "Bem-aventurado Francisco Zirano, presbítero e mártir",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-01-30-santa-jacinta-de-mariscotti-virgem",
    monthDay: "01-30",
    name: "Santa Jacinta de Mariscotti, virgem",
    qualifiers: ["virgem"],
    order: "third",
    observances: [{ jurisdiction: "OFS", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-02-04-sao-jose-de-leonissa-presbitero",
    monthDay: "02-04",
    name: "São José de Leonissa, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-02-06-sao-pedro-batista-sao-paulo-miki-e-seus-companheiros-martire",
    monthDay: "02-06",
    name: "São Pedro Batista, São Paulo Miki e seus companheiros, mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-02-07-santa-coleta-virgem",
    monthDay: "02-07",
    name: "Santa Coleta, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-02-09-bem-aventurado-leopoldo-de-alpandeire-religioso",
    monthDay: "02-09",
    name: "Bem-aventurado Leopoldo de Alpandeire, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-02-19-sao-conrado-de-placenca-eremita",
    monthDay: "02-19",
    name: "São Conrado de Placença, eremita",
    qualifiers: ["eremita"],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "memoria" }, { jurisdiction: "OFS", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-02-25-bem-aventurado-sebastiao-de-aparicio-religioso",
    monthDay: "02-25",
    name: "Bem-aventurado Sebastião de Aparício, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-03-02-santa-ines-de-praga-virgem",
    monthDay: "03-02",
    name: "Santa Inês de Praga, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-03-12-bem-aventurada-angela-salawa-virgem",
    monthDay: "03-12",
    name: "Bem-aventurada Ângela Salawa, virgem",
    qualifiers: ["virgem"],
    order: "third",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }, { jurisdiction: "TOR", rank: "memoria_facultativa" }, { jurisdiction: "OFS", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-03-18-sao-salvador-de-horta-religioso",
    monthDay: "03-18",
    name: "São Salvador de Horta, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-04-05-santa-maria-crescencia-hoss-virgem",
    monthDay: "04-05",
    name: "Santa Maria Crescência Höss, virgem",
    qualifiers: ["virgem"],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "memoria" }, { jurisdiction: "OFS", rank: "memoria" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-04-16-sao-benedito-jose-labre-secular-cordigero",
    monthDay: "04-16",
    name: "São Benedito José Labre, secular, cordígero",
    qualifiers: ["secular"],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "memoria_facultativa" }, { jurisdiction: "TOFr", rank: "memoria_facultativa" }, { jurisdiction: "OFS", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-04-21-sao-conrado-de-parzao-religioso",
    monthDay: "04-21",
    name: "São Conrado de Parzão, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-04-23-bem-aventurado-egidio-de-assis-religioso",
    monthDay: "04-23",
    name: "Bem-aventurado Egídio de Assis, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-04-24-sao-fidelis-de-sigmaringa-presbitero-e-martir",
    monthDay: "04-24",
    name: "São Fidélis de Sigmaringa, presbítero e mártir",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-04-28-bem-aventurado-luquesio-de-poggibonsi",
    monthDay: "04-28",
    name: "Bem-aventurado Luquésio de Poggibonsi",
    qualifiers: [],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "memoria_facultativa" }, { jurisdiction: "TOFr", rank: "memoria_facultativa" }, { jurisdiction: "OFS", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-04-30-bem-aventurado-bento-de-urbino-presbitero",
    monthDay: "04-30",
    name: "Bem-aventurado Bento de Urbino, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-04-bem-aventurados-tomas-bullaker-e-seus-companheiros-martires",
    monthDay: "05-04",
    name: "Bem-aventurados Tomás Bullaker e seus companheiros, mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-04-bem-aventurado-tomas-de-olera-religioso",
    monthDay: "05-04",
    name: "Bem-aventurado Tomás de Olera, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-06-bem-aventurada-maria-catarina-troiani-religiosa-virgem-e-fun",
    monthDay: "05-06",
    name: "Bem-aventurada Maria Catarina Troiani, religiosa, virgem e fundadora da Congregação das Irmãs Franciscanas Missionárias do Coração Imaculado de Maria",
    qualifiers: ["virgem", "religioso", "fundador"],
    order: null,
    observances: [{ jurisdiction: "FMCIM", rank: "festa" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-08-bem-aventurado-jeremias-de-valaquia-religioso",
    monthDay: "05-08",
    name: "Bem-aventurado Jeremias de Valaquia, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-09-santa-catarina-de-bolonha-virgem",
    monthDay: "05-09",
    name: "Santa Catarina de Bolonha, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-11-santo-inacio-de-laconi-religioso",
    monthDay: "05-11",
    name: "Santo Inácio de Láconi, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-12-sao-leopoldo-mandic-presbitero",
    monthDay: "05-12",
    name: "São Leopoldo Mandic, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-13-sao-pedro-regalato-presbitero",
    monthDay: "05-13",
    name: "São Pedro Regalato, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-16-santa-margarida-de-cortona",
    monthDay: "05-16",
    name: "Santa Margarida de Cortona",
    qualifiers: [],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "festa" }, { jurisdiction: "OFS", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-17-sao-pascoal-bailao-religioso",
    monthDay: "05-17",
    name: "São Pascoal Bailão, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-18-sao-felix-de-cantalicio-religioso",
    monthDay: "05-18",
    name: "São Félix de Cantalício, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-19-sao-crispim-de-viterbo-religioso",
    monthDay: "05-19",
    name: "São Crispim de Viterbo, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-19-santa-maria-bernarda-virgem-e-fundadora",
    monthDay: "05-19",
    name: "Santa Maria Bernarda, virgem e fundadora",
    qualifiers: ["virgem", "fundador"],
    order: null,
    observances: [{ jurisdiction: "FMM", rank: "solenidade" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-20-sao-bernardino-de-sena-presbitero",
    monthDay: "05-20",
    name: "São Bernardino de Sena, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "festa" }, { jurisdiction: "OFM", rank: "memoria" }, { jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-24-dedicacao-da-basilica-de-sao-francisco-em-assis",
    monthDay: "05-24",
    name: "DEDICAÇÃO DA BASÍLICA DE SÃO FRANCISCO, EM ASSIS",
    qualifiers: [],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-27-bem-aventurado-jose-tous-y-soler-presbitero",
    monthDay: "05-27",
    name: "Bem-aventurado José Tous y Soler, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-28-santa-maria-ana-de-jesus-paredes-virgem",
    monthDay: "05-28",
    name: "Santa Maria Ana de Jesus Paredes, virgem",
    qualifiers: ["virgem"],
    order: "third",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }, { jurisdiction: "TOR", rank: "memoria_facultativa" }, { jurisdiction: "TOFr", rank: "memoria_facultativa" }, { jurisdiction: "OFS", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-05-30-santa-camila-batista-varano-virgem",
    monthDay: "05-30",
    name: "Santa Camila Batista Varano, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-02-sao-felix-de-nicosia-religioso",
    monthDay: "06-02",
    name: "São Félix de Nicósia, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-07-bem-aventurados-miguel-tomaszek-e-zbigniew-strza-kowski-pres",
    monthDay: "06-07",
    name: "Bem-aventurados Miguel Tomaszek e Zbigniew Strzałkowski, presbíteros e mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-08-bem-aventurado-nicolau-de-gesturi-religioso",
    monthDay: "06-08",
    name: "Bem-aventurado Nicolau de Gésturi, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-12-bem-aventurada-iolanda-religiosa",
    monthDay: "06-12",
    name: "Bem-aventurada Iolanda, religiosa",
    qualifiers: ["religioso"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-12-bem-aventurado-antonio-bajewski-presbitero-e-companheiros-ma",
    monthDay: "06-12",
    name: "Bem-aventurado Antônio Bajewski, presbítero, e companheiros mártires",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-12-bem-aventurada-florida-cevoli-virgem",
    monthDay: "06-12",
    name: "Bem-aventurada Florida Cévoli, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }, { jurisdiction: "Cl.Cp.", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-13-santo-antonio-de-padua-de-lisboa-presbitero-e-doutor-da-igre",
    monthDay: "06-13",
    name: "SANTO ANTÔNIO DE PÁDUA (DE LISBOA), PRESBÍTERO E DOUTOR DA IGREJA",
    qualifiers: ["doutor", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-16-bem-aventurado-joao-de-parma-presbitero",
    monthDay: "06-16",
    name: "Bem-aventurado João de Parma, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-16-bem-aventurado-aniceto-koplin-presbitero-e-companheiros-mart",
    monthDay: "06-16",
    name: "Bem-aventurado Aniceto Koplin, presbítero, e companheiros mártires",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-26-bem-aventurado-andre-jacinto-longhin-bispo",
    monthDay: "06-26",
    name: "Bem-aventurado André Jacinto Longhin, bispo",
    qualifiers: ["bispo"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-26-bem-aventurado-tiago-de-ghazir-presbitero",
    monthDay: "06-26",
    name: "Bem-aventurado Tiago de Ghazir, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-06-30-bem-aventurado-raimundo-lulio-martir",
    monthDay: "06-30",
    name: "Bem-aventurado Raimundo Lúlio, mártir",
    qualifiers: ["martir"],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "memoria" }, { jurisdiction: "TOFr", rank: "memoria" }, { jurisdiction: "OFS", rank: "memoria" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-04-santa-isabel-de-portugal",
    monthDay: "07-04",
    name: "Santa Isabel de Portugal",
    qualifiers: [],
    order: "third",
    observances: [{ jurisdiction: "OFS", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-08-sao-gregorio-grassi-bispo-e-seus-companheiros-martires-da-or",
    monthDay: "07-08",
    name: "São Gregório Grassi, bispo, e seus companheiros, mártires, da Ordem I e Ordem III",
    qualifiers: ["martir", "bispo"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-09-santos-nicolau-pick-wilaldo-e-seus-companheiros-martires",
    monthDay: "07-09",
    name: "Santos Nicolau Pick, Wilaldo e seus companheiros, mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria" }, { jurisdiction: "OFMConv", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-10-santa-veronica-giuliani-virgem",
    monthDay: "07-10",
    name: "Santa Verônica Giuliani, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "OFMCap", rank: "festa" }, { jurisdiction: "Cl.Cp.", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-12-sao-joao-jones-e-sao-joao-wall-presbiteros-e-martires",
    monthDay: "07-12",
    name: "São João Jones e São João Wall, presbíteros e mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-13-bem-aventurada-angelina-de-montegiove-religiosa-e-fundadora",
    monthDay: "07-13",
    name: "Bem-aventurada Angelina de Montegiove, religiosa e fundadora",
    qualifiers: ["religioso", "fundador"],
    order: "third",
    observances: [{ jurisdiction: "Franciscanas da Bem-aventurada Angelina", rank: "festa" }, { jurisdiction: "TOR", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-13-bem-aventurado-emanuel-ruiz-e-companheiros-martires",
    monthDay: "07-13",
    name: "Bem-aventurado Emanuel Ruíz e companheiros, mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-14-sao-francisco-solano-presbitero",
    monthDay: "07-14",
    name: "São Francisco Solano, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-15-sao-boa-ventura-bispo-e-doutor-da-igreja",
    monthDay: "07-15",
    name: "SÃO BOA VENTURA, BISPO E DOUTOR DA IGREJA",
    qualifiers: ["doutor", "bispo"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-21-sao-lourenco-de-brindisi-presbitero-e-doutor-da-igreja",
    monthDay: "07-21",
    name: "São Lourenço de Bríndisi, presbítero e doutor da Igreja",
    qualifiers: ["doutor", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-23-santa-cunegundes-religiosa",
    monthDay: "07-23",
    name: "Santa Cunegundes, religiosa",
    qualifiers: ["religioso"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-24-bem-aventurada-luisa-de-saboia-religiosa",
    monthDay: "07-24",
    name: "Bem-aventurada Luísa de Saboia, religiosa",
    qualifiers: ["religioso"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-24-bem-aventurado-antonio-lucci-bispo",
    monthDay: "07-24",
    name: "Bem-aventurado Antônio Lucci, bispo",
    qualifiers: ["bispo"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-27-bem-aventurada-maria-madalena-martinengo-virgem",
    monthDay: "07-27",
    name: "Bem-aventurada Maria Madalena Martinengo, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-28-bem-aventurada-maria-teresa-kowalska-virgem",
    monthDay: "07-28",
    name: "Bem-aventurada Maria Teresa Kowalska, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }, { jurisdiction: "Cl.Cp.", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-07-30-bem-aventurado-francisco-solano-casey-presbitero",
    monthDay: "07-30",
    name: "Bem-aventurado Francisco Solano Casey, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-02-santa-maria-dos-anjos-da-porciuncula",
    monthDay: "08-02",
    name: "SANTA MARIA DOS ANJOS DA PORCIÚNCULA",
    qualifiers: [],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-07-bem-aventurados-agatangelo-e-cassiano-martires",
    monthDay: "08-07",
    name: "Bem-aventurados Agatângelo e Cassiano, mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-08-santo-pai-domingos-presbitero-e-fundador-da-ordem-dos-pregad",
    monthDay: "08-08",
    name: "SANTO PAI DOMINGOS, PRESBÍTERO E FUNDADOR DA ORDEM DOS PREGADORES",
    qualifiers: ["presbitero", "fundador"],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-11-santa-clara-de-assis-virgem",
    monthDay: "08-11",
    name: "SANTA CLARA DE ASSIS, VIRGEM",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "OSC", rank: "solenidade" }, { jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-13-santa-dulce-lopes-pontes-virgem",
    monthDay: "08-13",
    name: "Santa Dulce Lopes Pontes, virgem",
    qualifiers: ["virgem"],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-13-bem-aventurado-marcos-de-aviano-presbitero",
    monthDay: "08-13",
    name: "Bem-aventurado Marcos de Aviano, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-14-sao-maximiliano-maria-kolbe-presbitero-e-martir",
    monthDay: "08-14",
    name: "São Maximiliano Maria Kolbe, presbítero e mártir",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-17-santa-beatriz-da-silva-virgem-e-fundadora",
    monthDay: "08-17",
    name: "Santa Beatriz da Silva, virgem e fundadora",
    qualifiers: ["virgem", "fundador"],
    order: null,
    observances: [{ jurisdiction: "OIC", rank: "solenidade" }, { jurisdiction: "Ordem II", rank: "festa" }, { jurisdiction: "OFM", rank: "memoria" }, { jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-18-bem-aventurados-luis-armando-adam-e-nicolau-savouret-presbit",
    monthDay: "08-18",
    name: "Bem-aventurados Luís Armando Adam e Nicolau Savouret, presbíteros e mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-19-sao-luis-de-tolosa-bispo",
    monthDay: "08-19",
    name: "São Luís de Tolosa, bispo",
    qualifiers: ["bispo"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-23-bem-aventurado-bernardo-peroni-de-offida-religioso",
    monthDay: "08-23",
    name: "Bem-aventurado Bernardo Peroni de Offida, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-08-25-sao-luis-ix-rei-de-franca",
    monthDay: "08-25",
    name: "São Luís IX, rei de França",
    qualifiers: [],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "festa" }, { jurisdiction: "OFS", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-02-bem-aventurados-joao-francisco-burte-severino-girault-apolin",
    monthDay: "09-02",
    name: "Bem-aventurados João Francisco Burté, Severino Girault, Apolinário Morel de Posat e seus companheiros, mártires",
    qualifiers: ["martir"],
    order: "first",
    observances: [{ jurisdiction: "TOR", rank: "memoria" }, { jurisdiction: "TOFr", rank: "memoria" }, { jurisdiction: "OFS", rank: "memoria" }, { jurisdiction: "OFMConv", rank: "memoria_facultativa" }, { jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-04-santa-rosa-de-viterbo-virgem",
    monthDay: "09-04",
    name: "Santa Rosa de Viterbo, virgem",
    qualifiers: ["virgem"],
    order: "third",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }, { jurisdiction: "TOR", rank: "memoria_facultativa" }, { jurisdiction: "TOFr", rank: "memoria_facultativa" }, { jurisdiction: "OFS", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-17-impressao-das-chagas-de-nosso-pai-sao-francisco",
    monthDay: "09-17",
    name: "IMPRESSÃO DAS CHAGAS DE NOSSO PAI SÃO FRANCISCO",
    qualifiers: [],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-18-sao-jose-de-copertino-presbitero",
    monthDay: "09-18",
    name: "São José de Copertino, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "festa" }, { jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-19-sao-francisco-maria-de-camporosso-religioso",
    monthDay: "09-19",
    name: "São Francisco Maria de Camporosso, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria" }, { jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-22-santo-inacio-de-santhia-presbitero",
    monthDay: "09-22",
    name: "Santo Inácio de Santhiá, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-23-sao-pio-de-pietrelcina-presbitero",
    monthDay: "09-23",
    name: "São Pio de Pietrelcina, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-24-encontro-do-corpo-de-santa-clara",
    monthDay: "09-24",
    name: "Encontro do Corpo de Santa Clara",
    qualifiers: [],
    order: null,
    observances: [{ jurisdiction: "Ordem II", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-26-santo-elzeario-de-sabran-e-bem-aventurada-delfina-conjuges",
    monthDay: "09-26",
    name: "Santo Elzeário de Sabrán e Bem-aventurada Delfina, cônjuges",
    qualifiers: [],
    order: "third",
    observances: [{ jurisdiction: "OFS", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-26-bem-aventurado-aurelio-de-vinalesa-presbitero-e-companheiros",
    monthDay: "09-26",
    name: "Bem-aventurado Aurélio de Vinalesa, presbítero, e companheiros mártires",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-09-28-bem-aventurado-inocencio-de-berzo-presbitero",
    monthDay: "09-28",
    name: "Bem-aventurado Inocêncio de Berzo, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-04-nosso-pai-sao-francisco-de-assis-diacono-fundador-de-tres-or",
    monthDay: "10-04",
    name: "NOSSO PAI SÃO FRANCISCO DE ASSIS, DIÁCONO, FUNDADOR DE TRÊS ORDENS",
    qualifiers: ["fundador", "diacono"],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "solenidade" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-05-sao-benedito-o-negro-religioso",
    monthDay: "10-05",
    name: "São Benedito o Negro, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-06-santa-maria-francisca-das-cinco-chagas-virgem",
    monthDay: "10-06",
    name: "Santa Maria Francisca das Cinco Chagas, virgem",
    qualifiers: ["virgem"],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "memoria_facultativa" }, { jurisdiction: "TOFr", rank: "memoria_facultativa" }, { jurisdiction: "OFS", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-10-sao-daniel-presbitero-e-seus-companheiros-martires",
    monthDay: "10-10",
    name: "São Daniel, presbítero, e seus companheiros, mártires",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-13-sao-serafim-de-montegranaro-religioso",
    monthDay: "10-13",
    name: "São Serafim de Montegranaro, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria" }, { jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-19-sao-pedro-de-alcantara-presbitero",
    monthDay: "10-19",
    name: "São Pedro de Alcântara, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-20-bem-aventurado-contardo-ferrini",
    monthDay: "10-20",
    name: "Bem-aventurado Contardo Ferrini",
    qualifiers: [],
    order: "third",
    observances: [{ jurisdiction: "OFS", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-20-bem-aventurado-tiago-de-strepa-bispo",
    monthDay: "10-20",
    name: "Bem-aventurado Tiago de Strepa, bispo",
    qualifiers: ["bispo"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-22-bem-aventurada-josefina-leroux-virgem-e-martir",
    monthDay: "10-22",
    name: "Bem-aventurada Josefina Leroux, virgem e mártir",
    qualifiers: ["martir", "virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-23-sao-joao-de-capistrano-presbitero",
    monthDay: "10-23",
    name: "São João de Capistrano, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-25-santo-antonio-de-santana-galvao-presbitero",
    monthDay: "10-25",
    name: "Santo Antônio de Santana Galvão, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-25-bem-aventurada-maria-de-jesus-massia-ferragut-e-companheiras",
    monthDay: "10-25",
    name: "Bem-aventurada Maria de Jesus Massiá Ferragut e companheiras, virgens e mártires",
    qualifiers: ["martir", "virgem"],
    order: "second",
    observances: [{ jurisdiction: "Cl.Cp.", rank: "memoria" }, { jurisdiction: "OFMCap", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-26-bem-aventurado-boaventura-de-potenza-presbitero",
    monthDay: "10-26",
    name: "Bem-aventurado Boaventura de Potenza, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-30-dedicacao-da-igreja-propria-nas-igrejas-da-ordem",
    monthDay: "10-30",
    name: "DEDICAÇÃO DA IGREJA PRÓPRIA (nas igrejas da Ordem)",
    qualifiers: [],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "solenidade" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-10-31-santo-angelo-de-acri-presbitero",
    monthDay: "10-31",
    name: "Santo Ângelo de Acri, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMCap", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-06-bem-aventurado-afonso-lopez-presbitero-e-companheiros-martir",
    monthDay: "11-06",
    name: "Bem-aventurado Afonso Lopez, presbítero, e companheiros, mártires",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-07-bem-aventurada-maria-crucifixa-satellico-virgem",
    monthDay: "11-07",
    name: "Bem-aventurada Maria Crucifixa Satéllico, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-08-bem-aventurado-joao-duns-scotus-presbitero",
    monthDay: "11-08",
    name: "Bem-aventurado João Duns Scotus, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-13-sao-diogo-de-alcala-religioso",
    monthDay: "11-13",
    name: "São Diogo de Alcalá, religioso",
    qualifiers: ["religioso"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-14-sao-nicolau-tavelic-presbitero-e-seus-companheiros-martires",
    monthDay: "11-14",
    name: "São Nicolau Tavelic, presbítero, e seus companheiros, mártires",
    qualifiers: ["martir", "presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-17-santa-isabel-da-hungria",
    monthDay: "11-17",
    name: "SANTA ISABEL DA HUNGRIA",
    qualifiers: [],
    order: "third",
    observances: [{ jurisdiction: "TOR", rank: "solenidade" }, { jurisdiction: "OFS", rank: "solenidade" }, { jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-18-bem-aventurada-salome-de-cracovia-virgem",
    monthDay: "11-18",
    name: "Bem-aventurada Salomé de Cracóvia, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-20-santa-ines-de-assis-virgem",
    monthDay: "11-20",
    name: "Santa Inês de Assis, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Ordem II", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-25-comemoracao-de-todos-os-fieis-defuntos-da-ordem-serafica",
    monthDay: "11-25",
    name: "Comemoração de Todos os Fiéis Defuntos da Ordem Seráfica",
    qualifiers: [],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-26-sao-leonardo-de-porto-mauricio-presbitero",
    monthDay: "11-26",
    name: "São Leonardo de Porto Maurício, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria" }, { jurisdiction: "OFMConv", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-27-sao-francisco-antonio-fasani-presbitero",
    monthDay: "11-27",
    name: "São Francisco Antônio Fasani, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "FF", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-28-sao-tiago-das-marcas-presbitero",
    monthDay: "11-28",
    name: "São Tiago das Marcas, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFM", rank: "memoria" }, { jurisdiction: "OFMConv", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-11-29-todos-os-santos-da-ordem-serafica",
    monthDay: "11-29",
    name: "TODOS OS SANTOS DA ORDEM SERÁFICA",
    qualifiers: [],
    order: null,
    observances: [{ jurisdiction: "FF", rank: "festa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-12-02-bem-aventurado-rafael-chylinski-presbitero",
    monthDay: "12-02",
    name: "Bem-aventurado Rafael Chylinski, presbítero",
    qualifiers: ["presbitero"],
    order: "first",
    observances: [{ jurisdiction: "OFMConv", rank: "memoria_facultativa" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
  {
    id: "saint-12-02-bem-aventurada-maria-angela-astorch-virgem",
    monthDay: "12-02",
    name: "Bem-aventurada Maria Ângela Astorch, virgem",
    qualifiers: ["virgem"],
    order: "second",
    observances: [{ jurisdiction: "Cl.Cp.", rank: "memoria" }],
    shortHistory: null,
    premium: true,
    celebrationSlug: null,
  },
];
